### ISSUE TITLE
Inference Bugs: TypeError: tuple indices must be integers or slices, not tuple

### ISSUE THREAD

**Issue by Klayand** [viiika/Meissonic#1]
**I love Meissonic. Great Pioneers**
When I run the `inference.py`, I use the `diffusers=0.30.2`:

pip show diffusers
Name: diffusers
**Version: 0.30.2**
Summary: State-of-the-art diffusion in PyTorch and JAX.
Home-page: https://github.com/huggingface/diffusers
Author: The Hugging Face team (past and future) with the help of all our contributors (https://github.com/huggingface/diffusers/graphs/contributors)

But I get this issues:

  0%|                                                                                                                     | 0/48 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "inference.py", line 37, in <module>
    image = pipe(prompt=prompt,
  File "/home/xxx/anaconda3/envs/fine-tune/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/xxx/projects/meissonic/utils/pipeline.py", line 314, in __call__
    model_output = self.transformer( 
  File "/home/xxx/anaconda3/envs/fine-tune/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/xxx/anaconda3/envs/fine-tune/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xxx/projects/meissonic/utils/transformer.py", line 1141, in forward
    encoder_hidden_states, hidden_states = block(
  File "/home/xxx/anaconda3/envs/fine-tune/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/xxx/anaconda3/envs/fine-tune/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xxx/projects/meissonic/utils/transformer.py", line 501, in forward
    attn_output, context_attn_output = self.attn(
  File "/home/xxx/anaconda3/envs/fine-tune/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/xxx/anaconda3/envs/fine-tune/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xxx/.local/lib/python3.8/site-packages/diffusers/models/attention_processor.py", line 490, in forward
    return self.processor(
File "/home/xxx/.local/lib/python3.8/site-packages/diffusers/models/attention_processor.py", line 1846, in __call__
    query, key = apply_rope(query, key, image_rotary_emb)
  File "/home/xxx/.local/lib/python3.8/site-packages/diffusers/models/attention_processor.py", line 1702, in apply_rope
    xq_out = freqs_cis[..., 0] * xq_[..., 0] + freqs_cis[..., 1] * xq_[..., 1]
TypeError: tuple indices must be integers or slices, not tuple

**I love Meissonic. Great Pioneers!**

**Comment by Owen718** [comment]
Please compile and install diffusers from [diffusers](https://github.com/huggingface/diffusers).


1. git clone https://github.com/huggingface/diffusers.git
2. cd diffusers 
3. pip install -e .

It would be solved.

**Comment by Klayand** [comment]
> Please compile and install diffusers from [diffusers](https://github.com/huggingface/diffusers).
> 
>     1. git clone https://github.com/huggingface/diffusers.git
> 
>     2. cd diffusers
> 
>     3. pip install -e .
> 
> 
> It would be solved.

I have solved it. @Owen718
